### ISSUE TITLE
Comparison

### ISSUE THREAD

**Issue by jonashaag** [adefossez/julius#1]
Hey @adefossez I just stumbled across this courtesy of @mpariente's GitHub activity feed. I added it to this comparison of resample implementations: https://gist.github.com/jonashaag/2cde4daa72cebfb20641373d8dceeaae

Just FYI :)

**Comment by adefossez** [comment]
@jonashaag thanks a lot for that! By the way I just fixed an issue in the code that was particularly bad for high sampling rate in irreductible form, which is exactly the case you are covering.
The results are much better now, see screenshot here after. When you get a chance could you update your notebook with it?

<img width="900" alt="Screenshot 2020-10-26 at 22 38 16" src="https://user-images.githubusercontent.com/1990078/97231605-fcb61480-17db-11eb-990a-b3bd593bd7ea.png">

**Comment by jonashaag** [comment]
Cool! :-)

If you're interested we could also make it into a proper repo and collaboratively add new implementations from time to time. In the meantime I'll update the Gist.

**Comment by jonashaag** [comment]
Btw would you mind adding benchmark column with resampy `kaiser_fast` (which I have found to be good enough mostly)?

**Comment by jonashaag** [comment]
https://github.com/jonashaag/audio-resampling-in-python

Not sure why it doesn't render though...

**Comment by adefossez** [comment]
I'm only replying now about `kaiser_fast`. Actually when doing the benchmark I am setting the number of zero crossing in `julius` to the same value as `kaiser_best`. Comparing to `kaiser_fast`, and updating the number of zero crossings for julius just roughly scales both algorithm runtime by the same factor, so it has not much interest.
