### ISSUE TITLE
Add convenience function for high pass filter

### ISSUE THREAD

**Issue by iver56** [adefossez/julius#10]
As you say in the code, a high pass filter can be implemented by using a low pass filter and doing some subtraction. A convenience function that does this would be nice :) This makes it easier for developers with less DSP knowledge to apply high pass filtering

**Comment by iver56** [comment]
By the way, thanks for making julius. I found that its low pass filter is roughly 100x faster than the biquad one in torchaudio.

**Comment by iver56** [comment]
My motivation is data augmentation. The plan is to add LPF and HPF to https://github.com/asteroid-team/torch-audiomentations

**Comment by adefossez** [comment]
sure, that seems like a reasonable request. I'll try to add that this weekend.

Glad this is useful! I should definitely submit a PR to integrate that into torchaudio, which would be quite useful as biqad are a bit weird of filters, great for sound design, but for ML I think windowed ideal lowpass filters make more sense.

One thing I'm not super happy is the FFT based convolution, first I use some heuristic to select it, but it is really rough and not always making the best choice, and the FFT convolution can actually take a gigantic amount of memory. For filters with high frequencies it is not so much a problem, but if you start making filters around 40Hz, you will feel it. I'm curious if you have any feedback on that.

**Comment by iver56** [comment]
Thanks :)

I have no feedback on the memory consumption yet. But I might give some feedback after I get my hands dirty :)

Btw, for now I implemented a simple high-pass filter transform for data augmentation like this:
https://github.com/asteroid-team/torch-audiomentations/pull/81/files#diff-7e66b58be7c985a4740f0be1da259b64c1674cbe5a985ac3bf27fe9b7f081d16R37

Is that correct? Feel free to add comments to the PR 👍

**Comment by adefossez** [comment]
Yep, looking good. I just updated julius with implementations which would be very much equivalent.

I also changed from the default Pytorch unfold function to a custom one which can be 10 times faster, making FFTConv faster and use less memory :D so you should also benefit from this.

**Comment by iver56** [comment]
Thanks for this enhancement!

If I run some benchmarks (julius 0.2.3 vs. 0.2.4), I will post the results here
