### ISSUE TITLE
Bandpass filter

### ISSUE THREAD

**Issue by jaideep11061982** [adefossez/julius#15]
Do we have bandpass filter also available ?

```
def apply_bandpass(x, lf=20, hf=512, order=8, sr=2048):
    sos = signal.butter(order, [lf, hf], btype="bandpass", output="sos", fs=sr)
    normalization = np.sqrt((hf - lf) / (sr / 2))
    return signal.sosfiltfilt(sos, x) / normalization
```

**Comment by adefossez** [comment]
There is, see https://adefossez.github.io/julius/julius/filters.html

**Comment by adefossez** [comment]
In some sense, the windowed sinc band pass filter is optimal, it is the closest approximation with a finite impulse response  to exactly zeroing out low and high frequencies in the Fourier domain.
Other filters are interesting for their acoustic features, for instance those with resonnance, but it is outside of the scope of this project to provide those.
