### ISSUE TITLE
cuFFT error: CUFFT_EXEC_FAILED

### ISSUE THREAD

**Issue by ahikaml** [adefossez/julius#16]
Hi
I’m getting a RuntimeError: cuFFT error: CUFFT_EXEC_FAILED, when I try to use the bandpass_filter with fft=True (a single GPU)
The last function called is new_fft.irfft
Any idea what could be the root cause? 
Thanks

**Comment by adefossez** [comment]
Hello @ahikaml , sorry for the late reply. Do you get any error when running on CPU ? If you can provide a minimal example to reproduce it would be very helpful!

**Comment by ahikaml** [comment]
Thanks for the response.

After re-checking I see that I no longer get this error even when the fft=True (until now I've used this function with fft=False) 
Anyway, I've never got this error on CPU.
I'm closing this issue for now. 
Thanks
