### ISSUE TITLE
torchaudio

### ISSUE THREAD

**Issue by HudsonHuang** [adefossez/julius#4]
Nice work.
But it seems there're already resample implemented by conv1d in pytorch's official [torchaudio](https://pytorch.org/audio/stable/transforms.html#resample)
Is there any necessary to implement it again?

**Comment by adefossez** [comment]
First this project is a DSP hobby, so I'm quite happy to reimplement things that already exists.
From your question I decided to run a quick comparison. First in terms of speed, torchaudio seems to be slower, at least on CPU. I guess it is because it does multiple calls to `conv1d` followed `conv_transpose1d`, while julius has a single call to `conv1d`. I will open up a bug report to torchaudio on that issue.

```python
from torchaudio.compliance import kaldi
import torch
import julius
x = th.randn(1, 44100 * 10)
rolloff = 0.99  # lowpass filter freq used by torchaudio
zeros = 6  # use the same number of zero crossing as torchaudio
for from_sr, to_sr in [(5, 7), (7, 5)]:
    print("comparing for", from_sr, to_sr)
    %timeit kaldi.resample_waveform(x, from_sr, to_sr)
    %timeit julius.resample_frac(x, from_sr, to_sr, rolloff=rolloff, zeros=zeros)
    yt = kaldi.resample_waveform(x, from_sr, to_sr)
    yj = julius.resample_frac(x, from_sr, to_sr, rolloff=rolloff, zeros=zeros)
    print(torch.norm(yt - yj))
```

```bash
comparing for 5 7
32.4 ms ± 309 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
4.46 ms ± 44.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
tensor(8.7085e-05)
comparing for 7 5
12.9 ms ± 323 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
2.83 ms ± 43.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
tensor(5.1333e-05)
````

Julius implementation is also shorter in terms of code.

**Comment by adefossez** [comment]
Bug report opened https://github.com/pytorch/audio/issues/1057

**Comment by HudsonHuang** [comment]
Great, I agree that we can learn a lot to reimplement something, and it would be even better as share your idea to benefit the whole community.

**Comment by HudsonHuang** [comment]
Great, I agree that we can learn a lot to re-implement something, and it would be even better as share your idea to benefit the whole community. Thank you.

**Comment by adefossez** [comment]
The implementation from julius is now part of Torchaudio: https://github.com/pytorch/audio/pull/1087 :)
