### ISSUE TITLE
Time spent on repeated kernel construction

### ISSUE THREAD

**Issue by jonashaag** [adefossez/julius#5]
First, let me say THANK YOU for reducing the time spent resampling ~ 30x in my particular application, compared to using resampy with the `kaiser_fast` mode. And thereby also reducing total application runtime ~ 50%! <3

After swapping resampy for julius my application spent most of its time in `_init_kernels` because I was using the `resample_frac` interface. I've worked around this by caching `ResampleFrac` instances:

```py
def resample(wav_arr, from_sr, to_sr, _resamplers={}):
    try:
        resampler = _resamplers[(from_sr, to_sr)]
    except KeyError:
        resampler = _resamplers[(from_sr, to_sr)] = julius.resample.ResampleFrac(from_sr, to_sr)
    with torch.no_grad():
        return resampler(torch.from_numpy(wav_arr)).numpy()
```

I wonder what you think about caching those instances (or maybe only the kernels) by default, OR adding a hint to the documentation that you might want to use the `ResampleFrac` interface if you're repeatedly resampling between the same sample rates.

**Comment by adefossez** [comment]
Hey @jonashaag, thanks for the kind word, I'm glad this is so useful to you!
Adding an LRU cache on the kernels would be a possibility, although it would add quite a bit of complexity, and for most applications I know of, one usually converts from one fixed sample rate to another.
But I will mention it in the documentation, thanks for pointing that out!

**Comment by adefossez** [comment]
I have added the warning to the doc: https://github.com/adefossez/julius/commit/02dcd4bd759c90e26bbf43252b6c553c6be374e6

I'll close this issue as I do not plan on adding more advanced cache support.
