### ISSUE TITLE
Question about the window function

### ISSUE THREAD

**Issue by yoyololicon** [adefossez/julius#9]
Hi @adefossez , 
First of all, thanks for your wonderful implementation! I have started to use it a lot recently, it really saves my time.
Also, your `ResampleFrac` module support `torch.jit` which is another great thing to admire.

Although the speed of resampling is excellent, I have noticed that the quality of `julius` isn't as good as other famous packages (like `resampy`). From @jonashaag's [notebook](https://nbviewer.jupyter.org/github/jonashaag/audio-resampling-in-python/blob/master/Audio%20Resampling%20in%20Python.ipynb), we can see that `julius` frequency response main lobe is wider than others, which I think is a result from the window function.

Current `julius` window function is fixed to use hann window:
https://github.com/adefossez/julius/blob/29c6aade9b25ad41f46f1d57b08ab61970ac3adb/julius/resample.py#L105-L106
 
If we add an option of window functions, user can have more choice to control the quality besides raising number of zeros.

BTW: As a side note, can I ask why not using `fft_conv` in `ResampleFrac`? Sinc interpolation use very large kernel, and I think it suites perfectly to use FFT to accelerate sinc interpolation.

**Comment by adefossez** [comment]
Hey @yoyololicon, thank you for your feedback. I'm glad this is proving useful to you. Regarding the window, support for arbitrary window is definitely something I should add. Myself I mostly use julius to resample the input or output of a neural network, and the impact of the window is not really the limiting factor in that case. But I'll try to invest some time supporting kaiser.

Regarding `fft_conv` and `ResampleFrac`, this is an interesting question. In fact you can only use FFT if you want to apply a convolution with the input and the output being sampled over the same grid. A special case is when the input and output grids change by an integer amount i.e. you can upsample by some factor, or downsample by some factor (see [Stretch and Downsample theorem on Julius O Smith book](https://ccrma.stanford.edu/~jos/st/Fourier_Theorems.html)). This means if you want to change the sample ratio by a ratio U / D, you have to first upsample by U, then downsample by D. In the end I think it is not so efficient.

**Comment by yoyololicon** [comment]
> Hey @yoyololicon, thank you for your feedback. I'm glad this is proving useful to you. Regarding the window, support for arbitrary window is definitely something I should add. Myself I mostly use julius to resample the input or output of a neural network, and the impact of the window is not really the limiting factor in that case. But I'll try to invest some time supporting kaiser.
> 
Cool, I'm looking forward to it.

> Regarding `fft_conv` and `ResampleFrac`, this is an interesting question. In fact you can only use FFT if you want to apply a convolution with the input and the output being sampled over the same grid. A special case is when the input and output grids change by an integer amount i.e. you can upsample by some factor, or downsample by some factor (see [Stretch and Downsample theorem on Julius O Smith book](https://ccrma.stanford.edu/~jos/st/Fourier_Theorems.html)). This means if you want to change the sample ratio by a ratio U / D, you have to first upsample by U, then downsample by D. In the end I think it is not so efficient.

Thanks for the explaination. According to the reference link, I guess the main bottle neck is that we need to calculate the response of `h` in high samplerate `sr * U`, where `STRETCH` and `DOWNSAMPLE` operation on `x` can be done with smaller FFT size using some frequency domain property of DFT.

But, as I understand, `julius` already compute multiple shifted version of the sinc kernel (`h`), and operate in the same samplerate as input:
https://github.com/adefossez/julius/blob/29c6aade9b25ad41f46f1d57b08ab61970ac3adb/julius/resample.py#L118-L120

I don't know whether you have done that before, but I think replacing `conv1d` with your `fft_conv1d` should improve some performance speed. 

I also see that you do strided convolution in the time domain. If you do it in frequency domain using the property that `DOWNSAMPLE(x)` <=> `OverlapAndAdd(X)`, you can save roughly 10~20% of time in my experiences becuase of smaller FFT size (`n_fft / stride`). But there is no doubt that when number of stride is bigger than a certain threshold, direct convolution is more efficient.

Actually, I have developed another version of [fft_conv](https://github.com/yoyololicon/fft-conv-pytorch) which utilize frequency domain properties of DFT to do strided/dilated convolution, and can be a drop-in replacement for all PyTorch `ConvNd` / `ConvTransposeNd` module. If strided convolution is where your bottle neck is, I recommend you to give it a try. 😀

**Comment by yoyololicon** [comment]
After doing some benchmarks, I found out the fft method can improve the speed slightly only when the sample ratio is integer or reciprocal of integer, other than that,  it will greatly degrade the performance.
